name: build

on:
  push:
    branches:
    - '*'

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v4
    - name: Prepare
      id: prepare
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo ::set-output name=tag_name::${TAG}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DPASS }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/ysicing/caddy2-geoip
          ttl.sh/ysicing/caddy2-geoip
          ysicing/caddy2-geoip
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DPASS }}
        repository: ysicing/caddy2-geoip
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/caddy2-geoip'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
