name: tag build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: actions/checkout@v4
    - name: Prepare
      id: prepare
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo ::set-output name=tag_name::${TAG}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/ysicing/caddygeoip
          ghcr.io/ysicing/caddygeoip:${{ steps.prepare.outputs.tag_name }}
          ttl.sh/ysicing/caddygeoip
          ttl.sh/ysicing/caddygeoip:${{ steps.prepare.outputs.tag_name }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/ysicing/caddygeoip:${{ steps.prepare.outputs.tag_name }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
